name: Free RDP via Ngrok

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Download ngrok
        run: |
          Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip

      - name: Unzip ngrok
        run: Expand-Archive ngrok.zip -DestinationPath .

      - name: Connect ngrok (start RDP tunnel)
        run: |
          ./ngrok.exe authtoken 2wCX0ooIzCpg1KPtQjSPDGfnQX1_aghi9eszYBJdyVtxNRBh
          Start-Process -NoNewWindow -FilePath ./ngrok.exe -ArgumentList "tcp 3389 --log=stdout > ngrok.log" 
          Start-Sleep -Seconds 10

      - name: Show ngrok TCP address
        run: |
          Get-Content ngrok.log | Select-String "tcp://" | Select-Object -Last 1
